### ISSUE TITLE
About Density estimation algorithm

### ISSUE THREAD

**Issue by xiongzhu666** [google/sky-optimization#15]
Hi, thanks for your great working~！I almost implement your algorithm successfully ，but I face a little doubt about "DE"
1.  "DE" meas Density estimation algorithm， right？
2.  what is the |{sky}| in formula 8？
3. according formula 8, I can get the new “pi” of “undetermined” pixel，so should I make statistics the ”low“ and ”high“ one more time based on the formula 1？？（ low score is 0.3 and high score is 0.5 in your paper）or I don't need to change anything, just modify the  “pi” of “undetermined” pixel？？
 
thanks
best regards

**Comment by misaka-10032** [comment]
1. Yes
2. The number of annotated sky pixels. `{}` is the set operator; `||` is the cardinality. If you happen to do the downsampling (and you should due to the computational cost), that will be the sample size.
3. The threshold is purely empirical. You can tune the hyperparameters based on your dataset.
